In [1]:
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

# torch

In [1]:
from navec import Navec

navec = Navec.load('../data/navec_news_v1_1B_250K_300d_100q.tar')

In [7]:
import torch
from slovnet.model.emb import NavecEmbedding

emb = NavecEmbedding(navec)

input = torch.tensor([1, 2, 0])
output = emb(input)
output

tensor([[ 4.2000e-01,  3.6666e-01,  1.7728e-01, -3.8719e-01, -1.0762e-01,
          1.6954e-01, -4.6063e-01,  5.4519e-01, -2.1212e-01,  2.0965e-01,
          1.9658e-01,  2.7807e-01, -2.3802e-01,  3.5155e-01,  1.4491e-02,
         -6.2684e-01,  5.3035e-01,  1.9494e-01, -1.4463e-01,  4.2379e-01,
          9.9441e-03,  4.5641e-02,  4.4792e-01,  2.7315e-01, -1.8784e-01,
          1.9004e-01,  1.8792e-01, -3.4799e-01, -3.5956e-01, -8.2170e-01,
         -2.7642e-01,  8.9486e-02,  9.6691e-02, -4.0136e-01,  9.5777e-02,
         -7.3557e-02,  3.5036e-01, -5.7925e-01,  9.4073e-02, -5.3993e-02,
          4.5024e-02, -2.4080e-01,  1.7612e-01, -8.4551e-02,  7.0789e-02,
          2.8063e-01,  1.6482e-01,  6.2593e-02,  1.5403e-01,  2.8569e-01,
          1.8327e-01,  1.3949e-01,  1.6827e-01,  2.5427e-01,  8.4898e-02,
         -3.3665e-01, -1.0479e-01, -2.7931e-01,  3.4267e-01, -3.0430e-02,
          3.2533e-01, -1.5184e-01, -1.8352e-01, -3.3840e-01, -2.9217e-01,
         -8.0255e-01, -1.0667e-01, -1.

# name

In [20]:
from navec import Navec

model = Navec.load('./hudlit_12B_500K_300d_100q.tar')

In [22]:
from collections import Counter

vocab = model.vocab
counts = Counter(dict(zip(vocab.words, vocab.counts)))

In [30]:
names = []
for word, count in counts.most_common():
    if word.endswith(('нет', 'нёт')):
        names.append(word)

In [31]:
sorted(names, key=len)

['нет',
 'нёт',
 'гнет',
 'анет',
 'мнет',
 'гнёт',
 'инет',
 'жнет',
 'энет',
 'пнет',
 'тянет',
 'монет',
 'тонет',
 'аннет',
 'н-нет',
 'уснет',
 'минет',
 'сонет',
 'жанет',
 'сунет',
 'кенет',
 'линет',
 'кинет',
 'вынет',
 'льнет',
 'канет',
 'вянет',
 'бенет',
 'тенет',
 'ахнет',
 'ткнет',
 'дунет',
 'уснёт',
 'ухнет',
 'танет',
 'учнет',
 'денет',
 'агнет',
 'люнет',
 'нинет',
 'венет',
 'манет',
 'ранет',
 'хенет',
 'генет',
 'ренет',
 'рунет',
 'станет',
 'начнет',
 'пахнет',
 'планет',
 'рухнет',
 'вернет',
 'гибнет',
 'джанет',
 'стонет',
 'брюнет',
 'тронет',
 'лопнет',
 'начнёт',
 'беннет',
 'гаснет',
 'дженет',
 'кеннет',
 'заснет',
 'гвинет',
 'утонет',
 'корнет',
 'стынет',
 'рванет',
 'грянет',
 'линнет',
 'клюнет',
 'сохнет',
 'хлынет',
 'сгинет',
 'жаннет',
 'барнет',
 'глянет',
 'липнет',
 'лорнет',
 'плюнет',
 'гарнет',
 'двинет',
 'махнет',
 'пухнет',
 'чахнет',
 'вернёт',
 'джэнет',
 'виснет',
 'скинет',
 'нырнет',
 'кивнет',
 'шагнет',
 'ляпнет',
 'дернет',
 'к

# usage

In [19]:
from navec import Navec

path = 'hudlit_12B_500K_300d_100q.tar'
navec = Navec.load(path)
navec['навек']

In [3]:
navec['нааавееек']

KeyError: 'нааавееек'

In [4]:
'нааавееек' in navec

False

In [5]:
navec.get('нааавееек')

In [6]:
import torch

module = navec.as_torch
input = torch.tensor([1, 2, 3])
emb = module(input)
emb

tensor([[ 4.5801e-02,  8.6986e-01, -1.6292e-01,  7.4754e-02,  1.9809e-01,
         -3.5679e-01, -2.7921e-01,  2.6684e-01,  2.3908e-01,  1.4012e-01,
          4.3170e-02, -3.5350e-02, -3.5594e-01,  1.3268e-01,  1.3822e-01,
         -2.4049e-01, -3.0899e-01,  1.9540e-01,  1.3109e-01,  7.9764e-02,
          8.4988e-02, -1.2537e-02, -4.5903e-02,  2.0125e-01,  3.2131e-01,
          3.0770e-01,  4.2275e-02, -7.6240e-01, -4.7021e-01,  3.7311e-02,
         -3.2972e-01, -1.2205e-01, -7.5376e-01, -3.2217e-01,  1.1243e-01,
          6.1488e-03, -3.0781e-01, -1.5175e-01,  1.4202e-01,  2.8357e-01,
          6.4349e-02, -5.2810e-02,  2.0043e-01, -3.0974e-01, -2.2015e-01,
         -2.6252e-01, -3.2010e-01, -4.7782e-01,  2.8054e-02,  2.2679e-01,
         -2.7840e-01,  1.0294e-01, -1.1771e-01,  6.4093e-02,  1.3833e-01,
          6.0189e-02,  1.4421e-01,  1.7433e-01,  9.5102e-02,  4.8336e-04,
          1.5745e-02,  1.2606e-01,  2.2076e-01, -1.6991e-01,  8.8323e-02,
          2.2062e-01,  5.8458e-03,  1.

In [17]:
input = torch.tensor([[module.pad_id]])
emb = module(input)
emb

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [18]:
emb.shape

torch.Size([1, 1, 300])

In [9]:
navec.vocab.get('навек')

225823

In [11]:
navec.vocab.get('наааавеeeк')

500000

# meta

In [ ]:
{
    'id': 'news_1B_250k_300d_100q'
    'theme': 'news',
    'corpus_size': 10**9,
    'vocab_size': 250000,
    'dim': 300,
    'qdim': 100,

    'sources': [
        'lenta',
        '...'
    ]
    'version': ...
}

# compress vocab

In [94]:
from tqdm import tqdm_notebook as log_progress


def load_lines(path):
    with open(path) as file:
        for line in file:
            yield line.rstrip()


def load_vocab(path):
    lines = load_lines(path)
    for line in lines:
        word, count = line.split(None, 1)
        yield word, int(count)
        
        
def vocab_path(name):
    return 'vocabs/%s.txt' % name


# ['librusec', 'taiga_proza', 'news', 'wiki']
path = vocab_path('librusec')
records = load_vocab(path)
words, counts = [], []
for word, count in log_progress(records):
    words.append(word)
    counts.append(count)
pairs = list(zip(words, counts))

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [98]:
import gzip

text = '\n'.join(words)
bytes = text.encode('utf8')
data = gzip.compress(bytes)
%time gzip.decompress(data)
len(data) / 1024 / 1024

CPU times: user 48.3 ms, sys: 3.11 ms, total: 51.4 ms
Wall time: 54.4 ms


1.4799385070800781

In [106]:
import numpy as np
x = np.array(counts)
y = x.astype(np.uint32)
data = gzip.compress(y.tobytes())
%time np.frombuffer(gzip.decompress(data))
len(data) / 1024 / 1024

CPU times: user 18.1 ms, sys: 316 µs, total: 18.4 ms
Wall time: 18.9 ms


1.0917329788208008

In [99]:
import numpy as np
x = np.array(counts)
y = x.astype(np.uint32)
data = y.tobytes()
%time np.frombuffer(data)
len(data) / 1024 / 1024

CPU times: user 26 µs, sys: 51 µs, total: 77 µs
Wall time: 93 µs


1.9073486328125

In [110]:
from io import BytesIO

buffer = BytesIO()
file = gzip.GzipFile(mode='wb', fileobj=buffer)
text = '\n'.join(words)
bytes = text.encode('utf8')
file.write(bytes)
file.flush()
file.close()
data = buffer.getvalue()

In [111]:
len(data) / 1024 / 1024

1.4799442291259766

In [114]:
# buffer = BytesIO(data)
# file = gzip.GzipFile(mode='rb', fileobj=buffer)
# %time file.read()

# vocab

In [38]:
from collections import OrderedDict

def load_lines(path):
    with open(path) as file:
        for line in file:
            yield line.rstrip()


def load_vocab(path):
    lines = load_lines(path)
    for line in lines:
        word, _ = line.split(None, 1)
        yield word
        
        
def vocab_path(name):
    return 'vocabs/%s.txt' % name


vocabs = OrderedDict()
for name in ['librusec', 'taiga_proza', 'news', 'wiki']:
    words = set(load_vocab(vocab_path(name)))
    vocabs[name] = words

In [24]:
for a in vocabs:
    for b in vocabs:
        if a < b:
            print(len(vocabs[a] & vocabs[b]), len(vocabs[a]), len(vocabs[b]), len(vocabs[a] & vocabs[b]) / min(len(vocabs[a]), len(vocabs[b])), a, b, sep='\t')

412356	500000	500000	0.824712	librusec	taiga_proza
191170	500000	250000	0.76468	librusec	news
330875	500000	750000	0.66175	librusec	wiki
312689	500000	750000	0.625378	taiga_proza	wiki
190752	250000	500000	0.763008	news	taiga_proza
222456	250000	750000	0.889824	news	wiki


In [25]:
len({
    word
    for name in vocabs
    for word in vocabs[name]
})

1000550

In [47]:
from collections import Counter
from os.path import expanduser, join
from os import listdir

from nerus.load import load_raw
from navec.train.tokens import find_tokens


dir = expanduser('~/proj/nerus/data/dumps')
freqs = OrderedDict()
for filename in ['factru.raw.jsonl.gz', 'gareev.raw.jsonl.gz', 'ne5.raw.jsonl.gz']:
    print(filename)
    path = join(dir, filename)
    records = load_raw(path)
    counts = Counter()
    for record in records:
        text = record.source.text
        for span in record.source.spans:
            for word in find_tokens(text[span.start:span.stop]):
                counts[word.lower()] += 1
#         for word in find_tokens(record.source.text):
#             counts[word.lower()] += 1
    freqs[filename] = counts

factru.raw.jsonl.gz
gareev.raw.jsonl.gz
ne5.raw.jsonl.gz


In [40]:
def get_cover(counts, vocab):
    total = 0
    in_vocab = 0
    for word, count in counts.items():
        total += count
        if word in vocab:
            in_vocab += count
    return in_vocab / total


for filename in freqs:
    for vocab in vocabs:
        print(get_cover(freqs[filename], vocabs[vocab]), filename, vocab)

0.968189753110366 factru.raw.jsonl.gz librusec
0.9697553271079831 factru.raw.jsonl.gz taiga_proza
0.9747568511180692 factru.raw.jsonl.gz news
0.9830973426805952 factru.raw.jsonl.gz wiki
0.9497426581895246 gareev.raw.jsonl.gz librusec
0.9501059642749016 gareev.raw.jsonl.gz taiga_proza
0.9786860429912201 gareev.raw.jsonl.gz news
0.9785346654556464 gareev.raw.jsonl.gz wiki
0.9609940363354595 ne5.raw.jsonl.gz librusec
0.9631156803328214 ne5.raw.jsonl.gz taiga_proza
0.9823903548218972 ne5.raw.jsonl.gz news
0.9830499093689031 ne5.raw.jsonl.gz wiki


In [48]:
for filename in freqs:
    for vocab in vocabs:
        print(get_cover(freqs[filename], vocabs[vocab]), filename, vocab)

0.8886554621848739 factru.raw.jsonl.gz librusec
0.896503884572697 factru.raw.jsonl.gz taiga_proza
0.9456952592357698 factru.raw.jsonl.gz news
0.9630965593784684 factru.raw.jsonl.gz wiki
0.7333573227779777 gareev.raw.jsonl.gz librusec
0.7394746311622886 gareev.raw.jsonl.gz taiga_proza
0.9093198992443325 gareev.raw.jsonl.gz news
0.9042821158690176 gareev.raw.jsonl.gz wiki
0.853046763180741 ne5.raw.jsonl.gz librusec
0.8605316877449025 ne5.raw.jsonl.gz taiga_proza
0.9349820502592741 ne5.raw.jsonl.gz news
0.9406602688941552 ne5.raw.jsonl.gz wiki


In [7]:
from tqdm import tqdm_notebook as log_progress
from collections import Counter
from navec.train.glove import load_glove_vocab, load_glove_cooc

counts = Counter()
words = [word.decode('utf8') for word, _ in load_glove_vocab('vocabs/all.txt')]
records = load_glove_cooc('t')
for (source, target), weight in log_progress(records):
    if source != target:
        counts[words[source - 1], words[target - 1]] = weight

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [8]:
counts.most_common(100)

[(('align', 'center'), 85228.18531746174),
 (('and', 'the'), 63884.51111111233),
 (('associated', 'press'), 53738.162698412656),
 (('and', 'of'), 39386.50753968247),
 (('a', 'в'), 37609.58650794136),
 (('a', 'of'), 35463.098809523115),
 (('brent', 'на'), 32993.2865079365),
 (('a', 'и'), 30184.240873019022),
 (('associated', 'сообщает'), 29907.380158730157),
 (('a', 'the'), 26742.45873016205),
 (('b', 'd'), 25745.461904762054),
 (('a', 's'), 25536.29960317622),
 (('a', 'b'), 23779.796031747326),
 (('b', 'a'), 23779.796031747326),
 (('b', 'в'), 23646.107539682558),
 (('bloomberg', 'агентство'), 22488.352380952452),
 (('apple', 'в'), 22391.82896825614),
 (('a', 'm'), 21966.607539684526),
 (('brent', 'марки'), 21502.395238095225),
 (('agence', 'france-presse'), 21466.8369047619),
 (('align', 'left'), 21279.265476190423),
 (('b', 'и'), 20459.25912698414),
 (('bbc', 'news'), 19024.539682539675),
 (('and', 'in'), 18845.683333333596),
 (('align', 'right'), 17252.64087301582),
 (('a', 'in'), 16

# word2vec-fish-music-bass

In [ ]:
# https://graceavery.com/word2vec-fish-music-bass/
# https://habr.com/ru/company/piter/blog/475488/

In [3]:
from navec import Navec

navec = Navec.load('../data/models/navec/navec_hudlit_v1_12B_500K_300d_100q.tar')

In [5]:
kv = navec.as_gensim

In [6]:
def analogy(a, b, c):
    return kv.most_similar(positive=[c, b], negative=[a])

In [10]:
# analogy('мужчина', 'король', 'женщина')

In [9]:
# analogy('благодать', 'страдание', 'python')

In [19]:
analogy('мужчина', 'программист', 'женщина')

[('художница', 0.47785085439682007),
 ('домохозяйка', 0.47673672437667847),
 ('ученица', 0.4755125045776367),
 ('машинистка', 0.4550073742866516),
 ('студентка', 0.4502703547477722),
 ('журналистка', 0.4471040964126587),
 ('дипломированный', 0.4448159337043762),
 ('девятнадцатилетняя', 0.44397780299186707),
 ('работающая', 0.4419400095939636),
 ('хакер', 0.4407674968242645)]

In [23]:
analogy('мужчина', 'профессор', 'женщина')

[('доктор', 0.5405120849609375),
 ('профессора', 0.5230528712272644),
 ('макгонагалл', 0.5178957581520081),
 ('учительница', 0.4828588366508484),
 ('студентка', 0.48270758986473083),
 ('университета', 0.4779840111732483),
 ('госпожа', 0.47559359669685364),
 ('елена', 0.47392508387565613),
 ('профессором', 0.47029608488082886),
 ('анна', 0.46612581610679626)]